name: "Deploy CodigoFacilito"

on:                          #trigger
  push:                      ##cuando se realice un push en la rama indicada
    branches: ["main"]


jobs: 
  deploy-codigofacilito:                          #nombre del job
    runs-on: ubuntu-latest                        #runner: tipo de maquina virtual sobre la que se va a trabajar
    steps:          
      - uses: actions/checkout@v4                               #pasos
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
